"""
data_loader.py - Load raw dataset and strategy report for the dashboard.
Uses Streamlit caching to avoid re-reading on every interaction.
"""

import pandas as pd
import numpy as np
import streamlit as st
import sys, os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.config import RAW_DATA_PATH, STRATEGY_CSV_PATH


@st.cache_data
def load_raw_data() -> pd.DataFrame:
    """Load the raw 100K business financial dataset and add engineered features."""
    df = pd.read_csv(RAW_DATA_PATH)

    # Engineered features (same as ML pipeline)
    df["Profit"] = df["Monthly_Revenue"] - df["Monthly_Expense"]
    df["ProfitMargin"] = np.where(
        df["Monthly_Revenue"] != 0,
        df["Profit"] / df["Monthly_Revenue"],
        0.0,
    )
    df["CashRatio"] = np.where(
        df["OD_Required"] > 0,
        df["Cash_Inflow_Adjusted"] / df["OD_Required"],
        10.0,
    )
    df["CCC_Calculated"] = df["Inventory_Days"] + df["Receivable_Days"] - df["Payable_Days"]
    return df


@st.cache_data
def load_strategy_report() -> pd.DataFrame:
    """Load the sector-level strategy CSV generated by the ML pipeline."""
    return pd.read_csv(STRATEGY_CSV_PATH)
